### ISSUE TITLE
Mime-Type "text/markdown" and "text/x-markdown" interfere with VS code markdown blocks

### ISSUE THREAD

**Issue by ghost** [AnWeber/httpbook-monacorenderer#8]
When installing your extension and using it in Polyglot VS Code notebooks, all Markdown blocks stop rendering correctly.

Removing the "text/markdown" and "text/x-markdown" Mime-types from package.json fixes this problem.

Would you consider removing them? I could sent a PR.

**Comment by AnWeber** [comment]
@boehmet What is the problem? You should be able to change the display renderer at any time. Do you have a short example for me?

![change_output](https://github.com/AnWeber/httpbook-monacorenderer/assets/13434739/c7339819-4c82-459c-8568-6fe47d274829)

**Comment by ghost** [comment]
I am using the *.dib Notebook format and in this case even the "..." do not even display- I only get a big white box:
<img width="1012" alt="image" src="https://github.com/AnWeber/httpbook-monacorenderer/assets/107913724/b401ca66-f1ab-4e7e-bd06-f4f5aab8b3b7">
Note that I do get the ... selector on any other output type - but not on markdown

**Comment by AnWeber** [comment]
Ok, I have reproduced the problem. However, I must admit that it seems to me that Polyglot is making a special case of not supporting other renderers correctly. My renderer implements an [open interface from vscode used as output renderer](https://code.visualstudio.com/api/extension-guides/notebook#notebook-renderer). The example is similar to https://github.com/microsoft/vscode/issues/125876. However, Polyglot also uses the output renderers as code cell renderers and I don't see how to prevent this in my extension. Removing all mimetype that cause problems doesn't seem to be the solution.

**Comment by ghost** [comment]
I agree that this is not a real "solution". Do you know if there is any programmatic way to define the renderer (or priority) for a given MIME type?

**Comment by AnWeber** [comment]
No the only way to define the renderer for mimetypes is using package.json (static). I can remove the mimetypes but it feels hacky,

**Comment by ghost** [comment]
I have built a version of the renderer with markdown removed for myself. This works for me - I cannot really judge if removing them for everybody does make sense. I greatly appreciate your efforts and quick responses

**Comment by AnWeber** [comment]
I have now removed markdown from the list in the meantime.  I would now wait to see what comes out of my ticket dotnet/interactive#3288 and then add it back if necessary. I think that is the easiest thing to do. My use case where I would have needed the feature has been done for a long time.

**Comment by ghost** [comment]
Great. Thanks a lot for your efforts. Highly appreciated.
